/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./../views/403.vue')['default']
    404: typeof import('./../views/404.vue')['default']
    Contact: typeof import('./../views/Contact.vue')['default']
    Default: typeof import('./../components/layouts/default.vue')['default']
    Home: typeof import('./../views/Home.vue')['default']
    ImageDetail: typeof import('./../views/ImageDetail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwiperBanner: typeof import('./../components/swiperBanner.vue')['default']
  }
}
